name: General Tester
on:
  workflow_dispatch:
env:
  zip_dir: ${{ github.workspace }}/zips
 
jobs:
  create_artifacts:
    name: Generate Artifacts
    uses: ./.github/workflows/artifact_maker.yml
  prepare_all_artifacts:
    name: Download & Check Artifacts
    needs: [create_artifacts]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifact_dump
    - name: Zip artifacts
      shell: pwsh
      run: |
        $folders = Get-ChildItem -Directory -Path "${{ github.workspace }}/artifact_dump"
        foreach($dir in $folders)
        {
          $name = $dir.name
          $path = $dir.fullname
          7z a "${{ env.zip_dir }}/${name}.zip" "${path}/*"
        }
    - name: Generate release
      uses: softprops/action-gh-release@v1
      with:
        name: "Test Release"
        tag_name: test_tag
        fail_on_unmatched_files: true
        files: |
          ${{ env.zip_dir }}/*.zip
        