name: General Tester
on:
  workflow_dispatch:
env:
  zip_dir: ${{ github.workspace }}/zips
 
jobs:
  do_matrix:
    name: Matrix
    strategy:
      matrix:
        var: [one, two, three]
    runs-on: windows-latest
    outputs:
      test_output: ${{ steps.set_output.outputs.outty }}
    steps:
    - name: Echo
      run: echo ${{ matrix.var }}
    - name: Set output
      id: set_output
      if: matrix.var == 'two'
      run: echo "outty=Hi" >> $Env:GITHUB_OUTPUT
      
  check_output:
    name: Check output
    needs: [do_matrix]
    runs-on: windows-latest
    steps:
    - name: Print output
      run: echo "${{ needs.do_matrix.outputs.test_output }}"
    
  