name: General Tester
on:
  workflow_dispatch:
  
jobs:
  composite-test:
    name: Test nested composite reference
    runs-on: windows-latest
    steps:
    - name: Same ref test
      uses: oblivioncth/actions/test/outer@f1386ed8631156446bda54b6af2b60d068621e22