name: General Tester
on:
  workflow_dispatch:
  
jobs:
  create_artifacts:
    name: Generate Artifacts
    uses: ./.github/workflows/artifact_maker.yml
  download_all_artifacts:
    name: Download & Check Artifacts
    needs: [create_artifacts]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifact_dump
    - name: List artifact contents
      run: |
        ls -R