name: General Tester
on:
  workflow_dispatch:
env:
  zip_dir: ${{ github.workspace }}/zips
 
jobs:
  run-images-for-inspection:
    name: Start images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
    
  